# Generated by Django 3.2.9 on 2022-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermaster',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('userfullname', models.CharField(max_length=50)),
                ('emailid', models.EmailField(blank=True, max_length=50, null=True)),
                ('userpassword', models.CharField(blank=True, max_length=100, null=True)),
                ('activeuser', models.CharField(max_length=1)),
                ('createduser', models.CharField(blank=True, max_length=6, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('editeduser', models.CharField(blank=True, max_length=6, null=True)),
                ('editeddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usermaster',
                'managed': False,
            },
        ),
    ]
