# Generated by Django 3.2.9 on 2022-03-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcd_db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usermaster',
        ),
    ]
